### ISSUE TITLE
Using ANSI functions in PlatformManagerWindows.py

### ISSUE THREAD

**Issue by ruoygao** [glitchassassin/lackey#102]
Hi, 
Thanks for the great work of migrating sikuli to pure python. I found that there are random crash (access violation) in:
    hdc = self._gdi32.CreateDCA(ctypes.c_char_p(device_name.encode("utf-8")), 0, 0, 0) 
on a x64 system. It looks like a issue of using ANSI function instead of using Unicode ones, as the address is some format like 0x00007fff00000000, and the behavior disappeared after I inserted a line of print device_name. 

I tried to fix it by changing them to Unicode format as:
-        self._gdi32.CreateDCA.restype = ctypes.c_void_p
 -        hdc = self._gdi32.CreateDCA(ctypes.c_char_p(device_name.encode("utf-8")), 0, 0, 0) # Convert to bytestring for c_char_p type
 +        self._gdi32.CreateDCW.restype = ctypes.c_void_p
 +        hdc = self._gdi32.CreateDCW(ctypes.c_wchar_p(unicode(device_name)), 0, 0, 0) # Convert to bytestring for c_wchar_p type

I will test this for a while and see if this really fixed my issue.

**Comment by glitchassassin** [comment]
Thanks; I haven't seen this issue on my end, but let me know how your testing goes.

**Comment by ruoygao** [comment]
Hi there,

After this change, the access violation never happened so far. I'm not 100% positive that my issue was exactly caused by ANSI functions, so I will try to see if I can pinpoint the root cause if I had a chance.

**Comment by glitchassassin** [comment]
I went ahead and merged the proposed change into the `develop` branch. If it doesn't cause any issues for the automated tests, it'll roll out with the next version.

Thanks!

**Comment by glitchassassin** [comment]
This issue has been fixed with v0.7.0.
