### ISSUE TITLE
[Question] The _type function

### ISSUE THREAD

**Issue by GeorgSteyn** [glitchassassin/lackey#104]
I just want to know, maybe I understand wrong.
But from what I have seen the Python Generic type function was reassigned to _type.
So if i want to use "type" I would use it. _type(THING THAT I WANT TO CHECK TYPE  ).

Is this the correct method?

**Comment by nejch** [comment]
You found a bug. Python ignores 'private' variables (e.g. `_type`) when importing into the current namespace, which is how lackey/sikuli are typically used. From [PEP8](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles):

> In addition, the following special forms using leading or trailing underscores are recognized (these can generally be combined with any case convention):
> 
> `_single_leading_underscore`: weak "internal use" indicator. E.g. `from M import *` does not import objects whose name starts with an underscore.

```python
# Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32
>>> type('test')
<class 'str'>
>>> from lackey import *
>>> type('test')
[action] Typing 'test' with modifiers 'None'
>>> _type('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_type' is not defined
```
It works with importing in its own namespace:

```python
>>> type('test')
<class 'str'>
>>> import lackey
>>> lackey.type('test')
[action] Typing 'test' with modifiers 'None'
>>> lackey._type('test')
<class 'str'>
```

Changing `_type` to `type_` (and `_input` to`input_`) fixes this bug:

```python
>>> type('test')
<class 'str'>
>>> from lackey import *
>>> type('test')
[action] Typing 'test' with modifiers 'None'
>>> type_('test')
<class 'str'>
```

To keep backwards compatibility (if someone has used this in the past by providing a namespace with e.g. `import lackey`), both options would have to be available. I can submit a PR later if this is an acceptable solution?

**Comment by glitchassassin** [comment]
Good catch @nejch. Please do open a PR, I’ll try to get caught up on changes. Thanks!

**Comment by glitchassassin** [comment]
PR merged into the develop branch. This will roll out with the next version.

**Comment by glitchassassin** [comment]
This issue has been fixed with v0.7.0.

**Comment by GeorgSteyn** [comment]
Thank You Very Much!!! In my free time, I would try to contribute more to this repo. We use it for GUI testing with Robot Framework.

**Comment by glitchassassin** [comment]
Any help is welcome! My free time is somewhat less than it used to be. Take a look at some of the open issues, or feel free to open a new one for other enhancements.
