### ISSUE TITLE
Lackey online documentation missing

### ISSUE THREAD

**Issue by daxiarobin** [glitchassassin/lackey#107]
Just realized the API documentation on http://lackey.readthedocs.io/en/latest/lackey.html is not available any more. It used to have all the detailed explanation/usage for all the classes. But now I can only see the some of the  class names, no more explanations for any of them. 

Can the online documentation be updated? 

Thanks
Yifeng

**Comment by glitchassassin** [comment]
Found the issue; creating a pull request now. Good catch, thanks!

**Comment by daxiarobin** [comment]
Thanks
