### ISSUE TITLE
Exception thrown when attempting to use type(Key.CMD) on macOS

### ISSUE THREAD

**Issue by rwalton00** [glitchassassin/lackey#110]
**Description**

A ValueError is thrown when attempting to use Lackey 0.7.0 to automate the macOS 'cmd' key. The error message reads: 'ValueError: Unrecognized character: windows'.

**Notes**

- OS macOS 10.12
- Python version: 2.7
- Lackey version 0.7.0

**Steps to reproduce**

1. Launch a Terminal window.
2. Launch `python`
3. `import lackey`
4. `lackey.type('m', lackey.KeyModifier.CMD)`

**Result**
The following traceback is produced:

`[action] Typing 'm' with modifiers '{CMD}'

ValueError                                Traceback (most recent call last)
<ipython-input-2-44c19bb068da> in <module>()
----> 1 lackey.type("m", lackey.KeyModifier.CMD)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lackey/RegionMatching.pyc in type(self, *args)
    910         kb = keyboard
    911         if modifiers:
--> 912             kb.keyDown(modifiers)
    913         if Settings.TypeDelay > 0:
    914             typeSpeed = min(1.0, Settings.TypeDelay)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lackey/InputEmulation.pyc in keyDown(self, keys)
    299                 if special_code in self._SPECIAL_KEYCODES.keys():
    300                     # Found a special code
--> 301                     keyboard.press(self._SPECIAL_KEYCODES[special_code])
    302                 else:
    303                     # Wasn't a special code, just treat it as keystrokes

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keyboard/__init__.pyc in press(combination)
    629 def press(combination):
    630     """ Presses and holds down a key combination (see `send`). """
--> 631     send(combination, True, False)
    632 
    633 def release(combination):

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keyboard/__init__.pyc in send(combination, do_press, do_release)
    621         if do_press:
    622             for key in keys:
--> 623                 _os_keyboard.press(to_scan_code(key))
    624 
    625         if do_release:

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keyboard/__init__.pyc in to_scan_code(key)
    599         return key
    600     else:
--> 601         scan_code, modifiers = _os_keyboard.map_char(_normalize_name(key))
    602         return scan_code
    603 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keyboard/_darwinkeyboard.pyc in map_char(character)
    388     """ Returns a tuple of (scan_code, modifiers) where ``scan_code`` is a numeric scan code 
    389     and ``modifiers`` is an array of string modifier names (like 'shift') """
--> 390     return key_controller.map_char(character)
    391 
    392 def name_from_scancode(scan_code):

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keyboard/_darwinkeyboard.pyc in map_char(self, character)
    303             return (128+self.media_keys[character],[])
    304         else:
--> 305             return self.key_map.character_to_vk(character)
    306     def map_scan_code(self, scan_code):
    307         if scan_code >= 128:

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keyboard/_darwinkeyboard.pyc in character_to_vk(self, character)
    151             elif self.layout_specific_keys[vk][1] == character:
    152                 return (vk, ['shift'])
--> 153         raise ValueError("Unrecognized character: {}".format(character))
    154 
    155     def vk_to_character(self, vk, modifiers=[]):

ValueError: Unrecognized character: windows`

**Comment by glitchassassin** [comment]
On a hunch, try running `pip install --upgrade keyboard` (or `pip3` if appropriate).

**Comment by glitchassassin** [comment]
No, I take that back. It was actually broken in a more recent version of `keyboard`, and I was using an older one.

**Comment by glitchassassin** [comment]
I have [opened a pull request](https://github.com/boppreh/keyboard/pull/103) on the `keyboard` module that should fix this. In the mean time, you can use the following workaround to revert to the older version:

    pip uninstall keyboard
    pip install keyboard==0.10.0

**Comment by rwalton00** [comment]
Yes, rolling back to Keyboard 10.10.3 seems to have resolved this for me. Thanks!

**Comment by glitchassassin** [comment]
This should be resolved in the latest version of `keyboard`.
