### ISSUE TITLE
multi monitor error

### ISSUE THREAD

**Issue by howtoesc** [glitchassassin/lackey#114]
function isRegionValid is not considered the situation that monitors sequencing is reverse(the monitor 1 is at left of monitor 0)

**Comment by glitchassassin** [comment]
I'm not sure I understand the problem.

`isRegionValid` should just return a simple boolean if the region is at least partially inside any screen.

Are you looking at `clipRegionToScreen`?

**Comment by howtoesc** [comment]
![test](https://user-images.githubusercontent.com/5886416/34487911-4bc30f2e-f011-11e7-844a-a259c4c3a93f.PNG)

**Comment by glitchassassin** [comment]
This should still work; the coordinates for monitor 1 will just be negative on the X-axis (as the upper left corner of monitor 0 is considered the origin).

Are you seeing an error?

**Comment by howtoesc** [comment]
I may find the root cause.The function may need little fix like below
![default](https://user-images.githubusercontent.com/5886416/34508027-9109f92a-f076-11e7-86e8-50552902c2db.PNG)

**Comment by glitchassassin** [comment]
Ah, yes; that's why I wasn't seeing the issue. I just recently merged a pull request, #111, that fixes this problem.

Update to the latest version of `lackey` and see if that makes a difference!

**Comment by howtoesc** [comment]
I installed it from pip,I really checked if my source is old,but was careless that did not find the change；）
