### ISSUE TITLE
No module named tkinter - In linux

### ISSUE THREAD

**Issue by BonuV** [glitchassassin/lackey#116]
created few image testing scripts using lackey.
Scripts were working fine when i execute the scripts  in windows. Recently we needed to move to linux, when i am executing my scripts in linux. My script get errored out saying
"No module named tkinter"

searched for the module online and there is no module online.Wondering how its working on windows

**Comment by glitchassassin** [comment]
Tkinter is a module built in to most releases of Python. If your Linux distro comes with a stripped down version of Python, it might not include Tkinter.

That said, lackey does not yet support Linux. if you'd like to begin adding a Linux PlatformManager, check out the existing code & documentation to get an idea of what will be needed!

**Comment by BonuV** [comment]
Thank you Jon
