### ISSUE TITLE
How can I turn off the debug message?

### ISSUE THREAD

**Issue by chrischenubc** [glitchassassin/lackey#121]
I am using the `Region.exists()` and a `while` loop to perform an operation that looks for a desired object on the screen and waits until it appears if is not shown up yet. However, it is quite annoying that it continuously displays debug messages on the console. Like `Couldn't find '{}' with enough similarity.`

I would like to turn off these debug messages so that my log doesn't look that messy.
One way I can think of is to add an option flag to the function. For example  `exists(self, pattern, seconds=None,debug=True)`. The `debug` parameter is used to control this behavior. And the implementation looks like this: 
```python
if debug:
    Debug.info("Couldn't find '{}' with enough similarity.".format(pattern.path))
```

Not sure if this is the best way to go. If there any possible solutions?

**Comment by glitchassassin** [comment]
You should be able to set the global Settings flag to disable the Action, Info, and Debug logs individually:

```
Settings.ActionLogs = True (message prefix: [log])
Settings.InfoLogs = True (message prefix: [info])
Settings.DebugLogs = False (message prefix: [debug])
```

If this doesn't work, there may be a deeper issue I need to fix. Try it and let me know!

**Comment by glitchassassin** [comment]
This functionality is for compatibility with Sikuli script conventions:

http://sikulix-2014.readthedocs.io/en/latest/scripting.html#debuglog

**Comment by chrischenubc** [comment]
It works!
Thanks very much.
