### ISSUE TITLE
PlatformManagerDarwin should not resize the screenshot

### ISSUE THREAD

**Issue by Unkraut3** [glitchassassin/lackey#123]
The method _getVirtualScreenBitmap of the class PlatformManagerDarwin down-scales the screenshot it just took. This is probably a good idea for retina displays and the like. However, on older macs with normal screens, there should be no resizing happening. 

On my 2011 mac mini I have to comment out the following line for lackey to generate usefull screenshots: 
` im = im.resize((int(im.size[0]/2), int(im.size[1]/2)), Image.ANTIALIAS)`

I think one should compare the size of the screenshot with the virtual screen and only downscale the screenshot if the sizes are unequal.

The following might do the job:

```
if im.size[0] != screen_w:
      im = im.resize((int(im.size[0]/2), int(im.size[1]/2)), Image.ANTIALIAS)
```

**Comment by glitchassassin** [comment]
Thanks for the catch, @Unkraut3. I'll do some testing with this change and make sure it doesn't break anything on my end.

**Comment by glitchassassin** [comment]
On your end, does the generated screenshot appear as a mostly black image with the captured screenshot as about 1/4 of the image? Or is it just a half-sized screenshot?
