### ISSUE TITLE
OPENCV Installation Error on Windows also

### ISSUE THREAD

**Issue by Coder-Sayan31** [glitchassassin/lackey#125]
No Matching Distributions found for opencv-python.
I am unable to install Lackey because of OpenCV compatibility.
Is there a way around?

**Comment by glitchassassin** [comment]
What OS/Python version?

**Comment by Coder-Sayan31** [comment]
Windows 8.1 & also Windows 10 
My Python Version is 3.6

**Comment by glitchassassin** [comment]
The package doesn't support [Python 3.7 yet, waiting for AppVeyor support](https://github.com/skvark/opencv-python/issues/106). But I've used it with 3.6 so it should definitely work there.

**Comment by glitchassassin** [comment]
If you continue to have trouble installing opencv-python, your best bet will be opening an issue on [their repository](https://github.com/skvark/opencv-python).
