### ISSUE TITLE
Underscore and Question Mark issue seems happen again

### ISSUE THREAD

**Issue by jazz1215** [glitchassassin/lackey#134]
Hi,

I noticed there was an issue #64 .  It was closed sometime ago.  However, recently I installed Lackey system on a new PC and this issue happened again.

My configuration:
Window 10
Python 2.7.15 (32 bit)
Lackey 0.7.2
Keyboard 0.13.2

Could you please help confirm if the fix in Keyboard has been reverted or is version of my installation incorrect?

To reproduce, in Python console, when use type('_'), it prints -, when run type('?'), it prints /.

Thanks.

**Comment by glitchassassin** [comment]
This should be resolved in the current version of the `keyboard` library.
