### ISSUE TITLE
Screen capture will not save the screen into PNG

### ISSUE THREAD

**Issue by jopasi** [glitchassassin/lackey#135]
Hello,

Thank you for your lackey app, I really like to use it.
Now,  I have faced an interesting issue: I would like to save a screen or part of the screen into a file.
This method works using Sikulix IDE but fails with lackey:  ValueError: rename: embedded null character in ...   (It means for me the screen file was not created.)

s = Screen()
filename= s.capture(s.getBounds())
shutil.move(filename, r'C:\picturelib\image.png')

Using Sikulix IDE the filename is saved under C:\users\userprofile\AppData\Local\Temp\Sikulix... folder
But using lackey module the s.capture() will not save into this location because Sikulix is not run.
May I ask you to check and somehow fix this issue (to save screen image file into a library?

Thank you,
Lac

**Comment by maxdule** [comment]
You should use saveScreenCapture() method from the Screen module.

**Comment by glitchassassin** [comment]
That's a good temporary solution, but Lackey should properly replicate the original SikuliX behavior as well. Tagging this as a bug to fix.

**Comment by glitchassassin** [comment]
Fix now present in the Develop ring.

**Comment by glitchassassin** [comment]
Fix released
