### ISSUE TITLE
Mouse Library Overflow Error

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#137]
On every execution following log displayed:

> C:\Program Files\Python37\lib\site-packages\lackey\InputEmulation.py:8: DeprecationWarning: The mouse sub-library is deprecated and will be removed in future versions. Please use the standalone package `mouse`.
  from keyboard import mouse
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python37\lib\site-packages\keyboard\__init__.py", line 292, in listen
    _os_keyboard.listen(self.direct_callback)
  File "C:\Program Files\Python37\lib\site-packages\keyboard\_winkeyboard.py", line 560, in listen
    prepare_intercept(callback)
  File "C:\Program Files\Python37\lib\site-packages\keyboard\_winkeyboard.py", line 553, in prepare_intercept
    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert

**Comment by glitchassassin** [comment]
What version of `keyboard` do you have installed?

**Comment by glitchassassin** [comment]
I don't htink this is related to the `mouse` deprecation warning, but it does appear to be coming from the `keyboard` module.

**Comment by maxdule** [comment]
> What version of `keyboard` do you have installed?

It's 0.13.2

**Comment by glitchassassin** [comment]
Hmm. I'm not seeing the same error on my end. What version of Windows?

**Comment by maxdule** [comment]
Win 10, 1803 version

**Comment by maxdule** [comment]
But these warnings do exist in mouse.py within keyboard.

Lines 3 & 4
`import warnings
warnings.simplefilter('always', DeprecationWarning)
warnings.warn('The mouse sub-library is deprecated and will be removed in future versions. Please use the standalone package `mouse`.', DeprecationWarning, stacklevel=2)`

**Comment by glitchassassin** [comment]
Yes, that appears, but doesn't cause the subsequent crash; it's the ArgumentError I'm concerned about.

**Comment by glitchassassin** [comment]
I am unable to duplicate this issue so far. Does it happen after just `import lackey`?

**Comment by glitchassassin** [comment]
(To be clear, the mouse deprecation warning is being tracked in #127, I'm here investigating the ctypes.ArgumentError crash.)

**Comment by glitchassassin** [comment]
I take that back! I have successfully replicated the error. Investigating further.

**Comment by jemiele1** [comment]
I did some investigating...

This is a known issue in keyboard. See issue 186. The version of file _winkeyboard.py in the keyboard master branch has been modified to correct this problem. I was able to patch _winkeyboard.py for keyboard and the error for importing lackey disappeared!

**Comment by glitchassassin** [comment]
This has been fixed in the master branch of the `keyboard` library.

**Comment by RichFlickstein** [comment]
I am still observing this issue with Lackey version 0.7.3. Is this fix in the release?
I am using Windows 10, Python 3.6.5, and installed using pip.

> C:\dev\QA\trunk\esign_separated_tests\venv\lib\site-packages\lackey\InputEmulation.py:8: DeprecationWarning: The mouse sub-library is deprecated and will be removed in future versions. Please use the standalone package `mouse`.
  from keyboard import mouse
