### ISSUE TITLE
paste(img, data) has different behaviors in lackey

### ISSUE THREAD

**Issue by jopasi** [glitchassassin/lackey#138]
Hello,
I have recognized the following different behavior.
This example works well in Sikulix but lackey.

So, when there are fields to be filled in in the active windows and I click into one of empty field to be activate it, but does not paste any value in it. Then I issue this command
paste(next_field_img, data_field) the lackey does not search the next_field_img picture. It past the dafa_field value into the previous active field. 

in lackey the code looks like this:
paste(Patter("next_field_img.png").targetOffset(46,179), data_field)

What I do instead of this which always woks: click into the active field using: click(next_field_img) with target offset then Paste(data_field) 

Can you please fix this issue in Lackey?

Thank you

**Comment by glitchassassin** [comment]
Fix for this is now in the develop ring.

**Comment by glitchassassin** [comment]
Develop has been released with this fix.
