### ISSUE TITLE
doubleClick results in a TypeError

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#14]
Attempt to use doubleClick method always results with the following error:

> File "build\bdist.win32\egg\lackey\RegionMatching.py", line 516, in doubleClick
  File "build\bdist.win32\egg\lackey\PlatformManagerWindows.py", line 261, in pressKey
TypeError: object of type 'int' has no len()

NOTE:  Image does exist on the screen (Found match for pattern 'image.png' at (385,656) with confidence (0.894939541817). Target at (407,674))

OS: Windows 7

**Comment by glitchassassin** [comment]
Appreciate the catch. I've patched this issue with a hotfix and pushed it out to PyPi. You should be able to update shortly.

I'll be pushing out several more bugfixes and more features for Sikuli compatibility sometime next week as well.

Cheers!

**Comment by maxdule** [comment]
I can confirm that fix is working, in the updated version of code from this morning.

Thanks, that was super-fast!
