### ISSUE TITLE
Error when typing ALT key on Mac

### ISSUE THREAD

**Issue by genequ** [glitchassassin/lackey#142]
macOS 10.12, Lackey 0.7.3

>>> type(Key.ALT)
[action] Typing '{ALT}' with modifiers 'None'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/lackey/RegionMatching.py", line 918, in type
    kb.type(text, typeSpeed)
  File "/usr/local/lib/python2.7/site-packages/lackey/InputEmulation.py", line 365, in type
    keyboard.press_and_release(self._SPECIAL_KEYCODES[special_code])
  File "/usr/local/lib/python2.7/site-packages/keyboard/__init__.py", line 381, in send
    _os_keyboard.press(scan_codes[0])
IndexError: tuple index out of range

**Comment by RaiMan** [comment]
I guess, lackey does not allow to "type" special keys like ALT, CTRL, SHIFT or CMD (but I may be wrong ;-) Normally they are used in combination with normal keys as so called modifiers.
You have to check the lackey API docs.
RaiMan from SikuliX

**Comment by genequ** [comment]
Thanks for the comments @RaiMan
I encountered the problem when using `type('t', Key.CMD+Key.ALT)`, then narrowed down it is caused when sending Key.ALT. It occurs when using any combinations with ALT.
No problem for CMD and SHIFT etc.

**Comment by glitchassassin** [comment]
I've replicated this on my end; it appears to be an issue with the underlying `keyboard` library. I'll review and submit a patch.

**Comment by glitchassassin** [comment]
Fix has been pushed to the `keyboard` master branch.
