### ISSUE TITLE
Adjust the minimum of similarity

### ISSUE THREAD

**Issue by frank1121** [glitchassassin/lackey#155]
Hi，the minimum of similarity is 0.7，how can I adjust the similarity to 0.8?

**Comment by glitchassassin** [comment]
You should be able to set the similarity to anything you want by adjusting the Pattern:

lackey.find(lackey.Pattern("to_find.png").similar(0.8))

For more on this, see the docs for Lackey:

https://lackey.readthedocs.io/en/latest/lackey.html#lackey.Pattern.similar

Or the docs for Sikuli, upon which Lackey is based:

https://sikulix-2014.readthedocs.io/en/latest/pattern.html#pattern

**Comment by frank1121** [comment]
> You should be able to set the similarity to anything you want by adjusting the Pattern:
> 
> ```
> lackey.find(lackey.Pattern("to_find.png").similar(0.8))
> ```
> 
> For more on this, see the docs for Lackey:
> 
> https://lackey.readthedocs.io/en/latest/lackey.html#lackey.Pattern.similar
> 
> Or the docs for Sikuli, upon which Lackey is based:
> 
> https://sikulix-2014.readthedocs.io/en/latest/pattern.html#pattern

thanks a lot
