### ISSUE TITLE
Is Lackey still active/supported?

### ISSUE THREAD

**Issue by randyr90s** [glitchassassin/lackey#156]
Is this project still active?  It still appears to be working, but the last release was Nov. 2018.

**Comment by glitchassassin** [comment]
Hi there! It's not currently under active development, no. It should be functional in Windows and OS X, with the exception of a couple open issues, but I have not gotten Linux support working. I'm still around if you have questions or want to submit a PR for anything.

**Comment by randyr90s** [comment]
Hi Jon - thanks for the quick reply.  Absolutely love Lackey, especially as some sites now seem to be detecting and blocking Watir/Selenium.  There are a few Sikulix functions that aren't working/don't behave the same under Lackey (findAllByRow comes to mind), but in general it's solid.  Thanks again.

**Comment by glitchassassin** [comment]
Do feel free to report issues where Lackey's functionality doesn't line up with SikuliX. I can't make guarantees, but I or someone else may be able to tackle them at some point!
