### ISSUE TITLE
How To Remove Unwanted Printing ?

### ISSUE THREAD

**Issue by VarnaX** [glitchassassin/lackey#175]
![image](https://user-images.githubusercontent.com/56477171/135715635-19b01ed6-d5ae-4938-b316-f17666d4a628.png)
I want To Remove All In This Image And Just Print My Needs

**Comment by trots** [comment]
Look at [logging settings](https://github.com/glitchassassin/lackey/blob/master/lackey/SettingsDebug.py#L141).
Add the code below to the beginnig of your script to disable `action` and `info` log levels:
```
Settings.ActionLogs = False
Settings.InfoLogs = False
```

**Comment by VarnaX** [comment]
> Look at [logging settings](https://github.com/glitchassassin/lackey/blob/master/lackey/SettingsDebug.py#L141). Add the code below to the beginnig of your script to disable `action` and `info` log levels:
> 
> ```
> Settings.ActionLogs = False
> Settings.InfoLogs = False
> ```

Thanks A Lot :)
