### ISSUE TITLE
Could not be installed by "pip install Lackey"

### ISSUE THREAD

**Issue by chishui** [glitchassassin/lackey#2]
Using "pip install Lackey" fails to install.
See image below
<img width="728" alt="2016-08-17 00 03 59" src="https://cloud.githubusercontent.com/assets/637584/17727467/3ddb57bc-640e-11e6-81ad-9826b0f1bc76.png">

Using "pip3 install Lackey" works fine.

**Comment by glitchassassin** [comment]
What OS/Python version(s) are you using?

**Comment by chishui** [comment]
Mac El Capitan 10.11.6
I have both python 2.7.2 and python 3.5.1 installed.
And pip install should use python 2.7.2

**Comment by glitchassassin** [comment]
No worries. OS X/Linux support will be part of a future release.

Because of the OpenCV dependency, Lackey is not yet supported on Python 3. I'm hoping to find a workaround at some point in the future, but cross-platform support is a higher priority.

Cheers!
