### ISSUE TITLE
OCR ideas

### ISSUE THREAD

**Issue by jwstolk** [glitchassassin/lackey#24]
I noticed that OCR is still on the TODO.

I started using SikuliX for scripting complex export and import procedures for 3D cad programs, and quickly switched to lacky to drop the java runtime. It's wonderful and have not run into any problems yet. Now I'm cleaning up some scripts and moving parts into Python functions and would like to replace some of the images with OCR to make some of the functions more general.

Is there any plan for how to implement this? would opencv be suitable for this?

In my case it would be enough to render a Python string onto a blank image in the correct font, and search for the the rendered text, but that would not be compatible with SikuliX.
I guess selectRegion() is also required to make OCR run at an acceptable speed.

(I can so a fair bit of C and asm programming, and trying to get more experience in Python. The object oriented stuff is a bit new to me.)

**Comment by glitchassassin** [comment]
From my research into this, I don't think OpenCV itself does OCR natively. 

My plan for this implementation is to find/build a cross-platform Python wrapper for the Tesseract OCR library (which is also what Sikuli uses). That's how Lackey currently imports OpenCV for image recognition.

Last time I looked, existing Python Tesseract wrappers used a command-line Tesseract executable that had to be pre-installed. I'd prefer something that can be installed with `pip` and that will address the library directly (passing PIL Images) to avoid writing temporary files to disk.

If you know of a suitable wrapper, or want to take a stab at building one, please feel free! Otherwise, it's the next feature slated for development, so I'll probably get to it in late November or early December.

Glad to hear Lackey has been helpful for you!

Cheers,

**Comment by jwstolk** [comment]
I have more on my plate but can't resist to at least look into it.
I found so far:
PIL = Python Image Library
pillow = "the friendly PIL fork" (and already listed as reqirement for Lackey)
libtesseract has C and C++ bindings. (C++ makes most sense since Python is object oriented too?)

This page list several Python wrappers for Tesseract 3.0x:
https://github.com/tesseract-ocr/tesseract/wiki/AddOns#tesseract-wrappers
https://github.com/sirfz/tesserocr "A simple, Pillow-friendly, wrapper" "integrates directly with Tesseract's C++ API using Cython" MIT licence, Requires libtesseract and libleptonica

I'll do some more reading, but that looks like a good match. 
(I don't know anything about hoe it integrated with pip)

**Comment by glitchassassin** [comment]
After some review, I'm thinking Tesseract itself will have to be installed out-of-band one way or the other to allow it to manage its own data files.

PyOCR looks promising. I will review and see if I can get it working.

**Comment by glitchassassin** [comment]
I've begun implementing this in the [feature-ocr](https://github.com/glitchassassin/lackey/tree/feature-ocr) branch.

After installing Tesseract from the [UB-Mannheim](https://github.com/UB-Mannheim/tesseract/wiki) installer, `pyocr` worked out of the box. The only image enhancement I've included at the moment is scaling the screenshot up to 300DPI.

The OCR is far from perfect, and could probably benefit from training. The find(), findAll(), and text() methods should be working (more or less). Note that the more restricted your region is, the more accurate the OCR conversion will be.

Note that it currently runs very slowly (it takes nearly 9 seconds to OCR the whole screen on my 1600x900 laptop). Sikuli runs much more quickly - more research is needed to optimize this. May be an issue with `pyocr`.

**Comment by jwstolk** [comment]
wow! very nice.  I'm reading the new code, and will try it out tomorrow on a windows box. (currently trying to install opencv 3 on ubuntu, to have a first look at Linux support.)

**Comment by jwstolk** [comment]
I only had a little bit of time today. I can confirm that installation in Win8.1 works, I only needed to enable "add to path" in the tesseract installer, and after installing git for Windows open a new CMD window. then:
pip uninstall lackey
pip install git+https://github.com/glitchassassin/lackey.git@feature-ocr
pip install pyocr

I'm having trouble finding small text and with large numbers, it reports a 1.0 confidence while always pointing at the wrong number. (does find() currently return the first result or the best result?) More tomorrow.

**Comment by glitchassassin** [comment]
Find() currently returns the first result given a particular margin of error. That margin of error is calculated based on the "Levenshtein distance" between the two strings, so if you're searching for individual characters that would allow for mismatches. 

That should be fixed to sort by confidence before returning. Not sure how soon I'll get to it, so feel free to submit a pull request if you get to it first.

**Comment by glitchassassin** [comment]
I am researching the feasibility of building `tesseract` directly into a Python wheel, the way OpenCV is distributed in the `opencv-python` package on PyPi. Most existing Windows packages rely on a pre-installed tesseract distribution, which is a pain for end users.

Currently I am attempting to build an "all-in-one" package with the `tesseract` binary, `tessdata` folder, and Python wrapper (based on `[python-tesseract-sip](https://github.com/virtuald/python-tesseract-sip)`)

**Comment by glitchassassin** [comment]
Having issues with conflicting versions of Visual Studio between the up-to-date Tesseract build and the tesseract-sip wrapper. I will explore building a more current Python wrapper for this, but I'm not sure how soon it will be (or if it will support Python 2.7).

**Comment by glitchassassin** [comment]
Experimental OCR support has been released, with tesseract as an external dependency.

**Comment by krzcho** [comment]
findText within Region raises NotImplementedError
How to utilize tesseract then?
