### ISSUE TITLE
self.target should be self._target 

### ISSUE THREAD

**Issue by deepwater1118** [glitchassassin/lackey#25]
class Match(Region):
	""" Extended Region object with additional data on click target, match score """
	def __init__(self, score, target, rect):
		super(Match, self).__init__(rect[0][0], rect[0][1], rect[1][0], rect[1][1])
		self._score = float(score)
		if not target or not isinstance(target, Location):
			raise TypeError("Match expected target to be a Location object")
		self._target = target

	def getScore(self):
		""" Returns confidence score of the match """
		return self._score

	def getTarget(self):
		""" Returns the location of the match click target (center by default, but may be offset) """
		return self.getCenter().offset(self._target.x, self._target.y)

	def __repr__(self):
		return "Match[{},{} {}x{}] score={.2f}, target={}".format(self.x, self.y, self.w, self.h, self._score, **# self.target.getTuple())**

**Comment by glitchassassin** [comment]
This has been patched in a development branch and will be rolled out to `master` in the near future.

**Comment by glitchassassin** [comment]
Released v0.4.1a1 with this hotfix and updated Pypi. The new version should be available for update shortly.
