### ISSUE TITLE
can not input "@" character 

### ISSUE THREAD

**Issue by deepwater1118** [glitchassassin/lackey#26]
when I use type() function to input "@" character, I find it will input nothing. you can try it. thanks

**Comment by glitchassassin** [comment]
Lackey makes some minor modifications to the way Sikuli handles `type()`. It follows Microsoft's more flexible SendKeys pattern. This means that certain characters (`^`, `+`, `%`, `~`, and `@`) represent modifier keys (CTRL, SHIFT, ALT, ENTER, and WIN/META/CMD respectively). For example, to type() Ctrl+C, you'd use the string `^c`.

To enter those characters as a literal, just enclose them in brackets: `{@}`

I'll update the documentation to make this more clear.

**Comment by glitchassassin** [comment]
Documentation updated. Resolving.
