### ISSUE TITLE
Drag & Drop problem

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#29]
Drag & drop fails with following output:

Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 675, in dragDrop
    drag(dragFrom)
NameError: global name 'drag' is not defined

**Comment by glitchassassin** [comment]
Thanks! I'll add this to the next hotfix. I'm also adding a test case for dragDrop functionality.

**Comment by glitchassassin** [comment]
Resolved with v0.4.2a1. Closing issue.
