### ISSUE TITLE
Settings.MinSimilarity Parameter Ignored

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#32]
Settings.MinSimilarity parameter set globally seems to be ignored.

Hint - shouldn't the line 40 in RegionMatching.py be:
`self.similarity = Settings.MinSimilarity`

instead of:
`self.similarity = 0.7`

**Comment by glitchassassin** [comment]
Yes it should. Good catch!

**Comment by glitchassassin** [comment]
Resolved with latest update.
