### ISSUE TITLE
Value Error on Call to exists() within Region

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#33]
Traceback output on attempt to call exists() method within a region:

> Error
> Traceback (most recent call last):
>     ...
>     if target.exists(images.checkbox_black, 0.5):
>   File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 489, in exists
>     match = matcher.findBestMatch(needle,pattern.similarity)
>   File "C:\Python27\lib\site-packages\lackey\TemplateMatchers.py", line 92, in findBestMatch
>     matches_heatmap = ((numpy.ones if method == cv2.TM_SQDIFF_NORMED else numpy.zeros)((lvl_haystack.shape[0] - lvl_needle.shape[0] + 1,lvl_haystack.shape[1] - lvl_needle.shape[1] + 1),dtype=numpy.float32))
> ValueError: negative dimensions are not allowed

**Comment by glitchassassin** [comment]
Hmm. This might be poor error checking.

What size was the image you were searching for, and what size was the region you were searching in?

You can use `Region.getW()` and `Region.getH()` to measure the region.

**Comment by maxdule** [comment]
Thanks for quick response. You were right, region was not correctly calculated. Region dimensions were 20x21 (w x h), whereas image dimensions were 23x24.

Another question that pops-up, using Region.nearby() without set parameter in nearby() results in following error:

`  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 243, in nearby
    return Region(self.x-expand, self.y-expand, self.w+(2*expand), self.h+(2*expand)).clipRegionToScreen()
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
`
... as it seems that there's no check when no value is set.

**Comment by glitchassassin** [comment]
Thanks, I'll add a size check to raise a more descriptive error.

I really appreciate all the bug reports. Mind if I credit you in the README for the next release?

**Comment by glitchassassin** [comment]
Resolved with latest update.
