### ISSUE TITLE
About using self._pid in someApp.focus()

### ISSUE THREAD

**Issue by jazz1215** [glitchassassin/lackey#34]
While using someApp.focus(), it seems the PID is not being used for looking for the application if `_search` is not None. 

In the below sample code, after notePadx.open() is executed, below values are generated in the application instance:
self._search   str: C:\\Windows\\system32\\notepad.exe
self._pid   Int:3328

In _focus_instance method, `self._pid` will not be used to look for the application, even when the `PlatformManager.getWindowByTitle()` fails to find the window.

I would suggest that return value check to be added to confirm if `PlatformManager.focusWindow(PlatformManager.getWindowByTitle(re.escape(self._search)))` is successful. If unsuccessful then use `PlatformManager.focusWindow(PlatformManager.getWindowByPID(self._pid))`.
My temporary work around is to use 'self._pid' as the first preference.

Demo code: to switch between two notepad instances.

    def testFocus(self):
        notePadProgram = r'C:\Windows\system32\notepad.exe'
        notePad1 = App(notePadProgram)
        notePad2 = App(notePadProgram)
        notePad1.open()
        notePad1.focus()
        time.sleep(2)
        type('Note Pad 1')
        notePad2.open()
        notePad1.focus()
        time.sleep(2)        
        type('Note Pad 2')
        raw_input('Press Enter to focus on notePad1')
        notePad1.focus()
        raw_input('Press Enter to focus on notePad2')
        notePad2.focus()

**Comment by glitchassassin** [comment]
Thanks! I am working on rewriting the App class to fix some other issues so this is definitely helpful.

**Comment by glitchassassin** [comment]
I have pushed some changes to the develop ring. After some more testing I'll roll them out to master and release.

**Comment by glitchassassin** [comment]
Resolved with latest update.
