### ISSUE TITLE
scr.type() removes brackets from string or throws error

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#35]
Typing text into a box types same text without brackets, e.g.

> scr.type("some_text_(1)_end") 

results in typing

> "some_text_1_end"

Same goes for square brackets, where error is thrown for curly braces {}:

> File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 731, in type
>     kb.type(text, typeSpeed)
>   File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 1189, in type
>     return PlatformManager.typeKeys(text, delay)
>   File "C:\Python27\lib\site-packages\lackey\PlatformManagerWindows.py", line 340, in typeKeys
>     raise ValueError("Unrecognized special code {{{}}}".format(special_code))
> ValueError: Unrecognized special code {123}

**Comment by glitchassassin** [comment]
The `type()` method uses certain characters to represent special keys or key modifiers.

Curly braces are used around key names, like `{ENTER}`. To enter a literal open or close curly brace, you should be able to wrap it in curly braces: `{{}` or `{}}`. 

*Now that I think about it, though, I'm pretty sure I implemented this wrong. I don't think the close curly brace will work. I'll work on a fix for the next release.*

Parentheses are used for modifying multiple characters. For example, to type "abc" in all caps you could call `type("+(abc)")` and the `+` modifier will be applied to all characters in the list. To enter literal open or close parentheses, wrap them in curly braces: `{(}` or `{)}`

**Comment by maxdule** [comment]
Thanks for the quick response.

The problem was initially spotted on attempt to pull paths of the files from specific folder - in this case each string would have to be re-formatted in order to check for (any) brackets within the name, and auto-saving options by many software of simply adding (1) makes it difficult to rename all the existing files.

Additionally, attempt to enter `{(}` actually freezes PyCharm and keyboard completely.

Error in the end of the stacktrace is sth like (PlatformManagerWindows.py line 336):

`self.pressKeyCode(self._SPECIAL_KEYCODES[special_code])
KeyError: '('`

**Comment by glitchassassin** [comment]
Well that was a silly copy-paste mistake. Easily fixed.

At any rate, you've presented a good counter-argument to the way I have this set up. Let me take a closer look at Sikuli's functionality and figure out the best way to resolve this.

**Comment by glitchassassin** [comment]
I am taking a little bit longer on this to implement the [keyboard](https://github.com/boppreh/keyboard) module, which should cover the low-level input simulation functionality across multiple platforms.

**Comment by glitchassassin** [comment]
I've pushed a new commit to the `develop` branch. 

I've rewritten all the keyboard and mouse code in PlatformManagerWindows.py to use the `keyboard` module instead of `ctypes`. Since this is already cross-platform, it should really go directly into the Keyboard and Mouse classes in RegionMatching.py, but for the sake of breaking as little as possible I'm starting here.

I'll work with this for a while and if `keyboard` is performing as expected I'll move the code into RegionMatching.py. Then I'll roll this out to `master`.

**Comment by glitchassassin** [comment]
Resolved with latest update.

Note that an issue with the `keyboard` library was identified while I was at it, preventing a few applications (like Citrix) from registering certain keys. A pull request has been submitted today, so the `pip` version should be up to date soon.
