### ISSUE TITLE
Having trouble installing via pip (python 2.7). No module keyboard/ PIL

### ISSUE THREAD

**Issue by Moondra** [glitchassassin/lackey#38]
Hi,

When trying to install lackey via pip, I was getting an error that said something along the lines of no module named keyboard. I managed to fix this error by 'pip install keyboard.' However, I ran into another error, soon after; 'no module named PIL'

I tried 'PIP install PIL' but am running into the following error:

Could not find a version that satisfied the requirement PIL...no matching distribution found for PIL.

Any ideas what I'm doing wrong? Thanks.

**Comment by glitchassassin** [comment]
It's not you, it's me.

While trying to streamline versioning I accidentally broke the pip install if the requirements aren't already installed. I've created a hotfix that should fix this. Pushing it out shortly.

**Comment by glitchassassin** [comment]
I've pushed the new version to Pypi, but I'm having some weird issues on my end. It keeps trying to install version 0.5.0 unless I explicitly tell it `pip install --upgrade lackey`, in which case it downloads and installs 0.5.1.

Can you try it and see if it does the same thing for you?

**Comment by Moondra** [comment]
Hi, what exactly would you like me to try out?  You want me to try to install lackey once again?

**Comment by glitchassassin** [comment]
Yes. Try it with `pip install lackey` first, and see if it correctly installs version 0.5.1.

If that doesn't work, try `pip install --upgrade lackey`.

It might just have been Pypi updating slowly.

**Comment by Moondra** [comment]
It seems to have installed 0.5.1 but I'm now getting the following error when I try to import lackey:

```Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import lackey
  File "C:\Python27\lib\site-packages\lackey\__init__.py", line 18, in <module>
    from .PlatformManagerWindows import PlatformManagerWindows
  File "C:\Python27\lib\site-packages\lackey\PlatformManagerWindows.py", line 16, in <module>
    from .Settings import Debug
  File "C:\Python27\lib\site-packages\lackey\Settings.py", line 126, in <module>
    class SettingsMaster(object):
  File "C:\Python27\lib\site-packages\lackey\Settings.py", line 159, in SettingsMaster
    BundlePath = os.path.dirname(os.path.abspath(os.path.join(os.getcwd(), __main__.__file__)))
AttributeError: 'module' object has no attribute '__file__'```

**Comment by glitchassassin** [comment]
This seems to be a separate issue, affecting the Python console specifically. Lackey imports in scripts properly.

**Comment by Moondra** [comment]
It seems I got the error when I was writing code directly through shell. By creating a file via Idle and saving it, the error disappeared.

**Comment by glitchassassin** [comment]
Tracking this in a new issue, #42. Closing this task as the original problem has been fixed.
