### ISSUE TITLE
TypeError: bytes or integer address expected instead of str instance

### ISSUE THREAD

**Issue by BosworthM** [glitchassassin/lackey#50]
Hello, i'm using python 3.5.x, and windows 7 x64.

When i use this piece of code: 
```
import lackey

pattern = lackey.Pattern(r'C:\Users\rainman\Documents\cam\my.png')
screen = lackey.Screen()
screen.click(pattern) # or screen.find(patter) or screen.capture()
```
Error happens:
```
hdc = self._gdi32.CreateDCA(ctypes.c_char_p(device_name), 0, 0, 0)
TypeError: bytes or integer address expected instead of str instance
```

**Comment by glitchassassin** [comment]
This is a known issue with Python x64 (see #47). I'm working on a fix.

**Comment by BosworthM** [comment]
Oh, thanks.

**Comment by glitchassassin** [comment]
As noted in the other thread, I've pushed the fix to the develop branch. I'll roll out a new release later this week after more thorough testing.

**Comment by glitchassassin** [comment]
This has been fixed in the latest release.
