### ISSUE TITLE
Key PRINTSCREEN/COMMAND & KeyModifers Problem

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#52]
There are issues with following keys - Key.PRINTSCREEN & Key.COMMAND -> typing those in text editor results in typing empty curly braces - {}.

The modifiers+brackets doesn't seem to work with current version (0.5.3)? E.g. typing "+(abc)" results in actually seeing "+(abc)" typed, instead of "ABC" (input string in caps).

**Comment by glitchassassin** [comment]
The parentheses syntax was removed with version 0.5.0 for Sikuli compatibility. That was an innovation of mine which Sikuli didn't provide, and caused problems with using Lackey as a drop-in replacement for Sikuli.

The other key issues are just incorrect key definitions. Should be easy to fix!

**Comment by glitchassassin** [comment]
I am updating key codes to better reflect [the Sikuli documentation](http://sikulix-2014.readthedocs.io/en/latest/keys.html).

`WIN`, `CMD`, and `META` will now all (on Windows) trigger the WIN key. (There is no `Key.COMMAND`.)

Key.PRINTSCREEN seems to be an issue with the underlying `keyboard` library. I've opened an issue and will pursue.

**Comment by glitchassassin** [comment]
The [bug with keyboard](https://github.com/boppreh/keyboard/issues/41) has been fixed. These changes should all be complete in `develop` and will be rolled out with the next release.

**Comment by glitchassassin** [comment]
These have been fixed with the latest release.
