### ISSUE TITLE
Issue in finding a solid-colour image

### ISSUE THREAD

**Issue by jazz1215** [glitchassassin/lackey#59]
I have encountered a trouble in finding a mono-colour image.  

1. Set the desktop background to a solid colour.  
2. Take a screenshot1 of the blank area of the desktop, e.g. 1500x900 pixels, without any icon.  The file is a solid-colour image and its size is about 5k.
3. Take another screenshot2 including left side shortcut icons, e.g. 1900x900 pixels.  The file size is about 90k.
4. Open a program on the desktop, e.g. notepad 1000x800 pixels, and position it in the 1500x900 area.
5. Run find(screenshot1.png) and find(screenshot2.png).

The expected result is that both 'find' will fail, because there is a significant notepad dialog in the region blocking the background.

The actual outcome was that only the second 'find' failed.  The first 'find' was successful and it reported:
Found match for pattern 'C:\temp\testPNG.sikuli\monoBG.png' at (0,0) with confidence (1.0). Target at (750, 450)

Tested using Sikuli, it was able to fail the find(screenshot1).

Issue was found in 0.4.0a1.  (It has been working well for me so I haven't upgraded it yet.)

Thanks.

**Comment by glitchassassin** [comment]
Hmm. Sikuli switches to from the default CCOEFF_NORMED method to SQDIFF_NORMED to match solid blocks of color. I'm guessing that'll probably be the fix here. I'm not familiar with the details of the two matching methods.

I'll work on this and see what I can come up with.

**Comment by glitchassassin** [comment]
The TemplateMatcher is now switching to SQDIFF_NORMED for solid-color matching, and inverting the image if the `needle` is all black. This should now mirror Sikuli's behavior.

The code is in the `develop` ring, and after some testing it'll be rolled out with the next release.

Thanks!

**Comment by glitchassassin** [comment]
This has been rolled out with the latest release.
