### ISSUE TITLE
Type Mismatch for Underscore and Question Mark

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#64]
It seems that underscore (_) is being typed as minus (-) and question mark (?) is being typed as forward slash (/) in current (0.5.4) version.

**Comment by glitchassassin** [comment]
Thanks for the report. This looks to be related to an issue with `keyboard`'s handling of numpad keys. Tracked in [issue 41](https://github.com/boppreh/keyboard/issues/41) on its GitHub issue tracker. I'll leave this open until it's resolved.

**Comment by glitchassassin** [comment]
The patch has been merged into `keyboard`'s master branch, but a new version has not yet been deployed to Pypi.

**Comment by glitchassassin** [comment]
This has been fixed in the latest version of `keyboard`.
