### ISSUE TITLE
Lackey Paste(text) function is not working poperly

### ISSUE THREAD

**Issue by nefsal22** [glitchassassin/lackey#68]
Hi,

I am trying to automate a tool using Lackey and using below code to paste the input values.

                              paste("test1") 
                              type(Key.TAB)
                              paste("test2") 
                              type(Key.TAB)

Here the paste function is not working instantly. Ideally the "test1" should be pasted and after a TAB, "test2" should be pasted. But instead, the programming is processing all the TABs and at the end pasting only "test2".

Am I doing something wrong? I have tried to include a sleep() after each paste, but that's not working too.

Can you help me on this?

**Comment by glitchassassin** [comment]
You're doing it right. Let's try some troubleshooting steps - sometimes automating programs can be finicky.

0. Can you paste into this field manually? (dumb question, I know, but sometimes it's the simple things)
1. Try replacing your `paste()` calls with `type()`. Is this more successful?
2. Try putting a `sleep(0.3)` *before* the `paste()` (to give the field time to focus).
3. If you're using Sikuli as well, does this script work in Sikuli?

**Comment by nefsal22** [comment]
0. I like the question, But ya I can definitely  paste there manually

1. the type() is working in this scenario and my automated tool already have that. Since its taking a lot of time for typing(my inputs are really large), I though I could replace it with paste(). I also tried the combination of getclipboard() and ospaste() too.

2. I already tried the sleep(), which also gave me a wrong result.

3.  I am not using Sikuli and i don't think I have the liberty to use it for this tool

**Comment by glitchassassin** [comment]
That's when I usually switch to `paste()` too. Let's try to rule out a simple timing issue by using really exaggerated delays:

    sleep(2)
    paste("test1")
    sleep(2)
    type(Key.TAB)
    sleep(2)
    paste("test2")
    sleep(2)
    type(Key.TAB)

If this works, then it's just a matter of adjusting the sleep() down until you find something that works reliably without waiting too long. If not, then we know there's something else weird going on. Let me know.

**Comment by nefsal22** [comment]
I have tried it with Sleep(5) and it gave me the same issue. Th program will wait for some time and then will execute all the commands and will paste at last.

Anyway I will try with sleep(2) and let you know.

**Comment by nefsal22** [comment]
No, this trick is also not working... I think its something else

**Comment by glitchassassin** [comment]
It executes all the commands at once, without a delay in between?

**Comment by nefsal22** [comment]
no.. where ever we specify the delay, it will wait. and after that without pasting, it will execute other commands(like TAB or ENTER) and then paste the text at last.

**Comment by glitchassassin** [comment]
Ah. And is it only this target application that's affected? If you run it in Notepad, will it execute properly?

I have a hunch that this may be related to the Tkinter clipboard code. I ran into some similar (not quite identical) issues with copy-pasting in a different application.

**Comment by nefsal22** [comment]
The Notepad is working perfectly with this and didn't show any glitches. 

Even I have a doubt on the clipboard related code. But I am not sure about it

**Comment by glitchassassin** [comment]
I'll test a replacement to the clipboard code and see if we can get a new version rolled out tomorrow. I'll keep you posted.

**Comment by glitchassassin** [comment]
Version 0.5.5 has been rolled out to Pypi with the new clipboard code. Please give it a try when you have a few minutes and let me know if it works any better for you.

**Comment by nefsal22** [comment]
Bravo! It worked :) 

Thanks
