### ISSUE TITLE
wait() always expects Pattern object as argument

### ISSUE THREAD

**Issue by nejch** [glitchassassin/lackey#70]
Hi Jon,
Thanks for this project, can't wait to get rid of the Java dependencies.
I'm trying to convert my sikulix scripts and found this tiny issue.

Lackey's `wait()` always expects a Pattern object as an argument so you cannot do `wait(2)` as you would with Sikulix (see e.g. [this](https://answers.launchpad.net/sikuli/+question/235023)):

```
>>> wait(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lackey\RegionMatching.py", line 462, in wait
    raise FindFailed("Could not find pattern '{}'".format(path))
lackey.Exceptions.FindFailed: Could not find pattern '2'
```
I saw this was actually implemented in `exists()`, `waitVanish()` and `findAll()`, but the type-checking misses floats:
```
>>> exists(2)
>>> exists(2.3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lackey\RegionMatching.py", line 522, in exists
    raise TypeError("find expected a string [image path] or Pattern object")
TypeError: find expected a string [image path] or Pattern object
```

**Comment by glitchassassin** [comment]
Good catch, thanks! 

Wait is actually the only one of those routines that should have this feature, according to the Sikuli specs, so I removed those lines from `exists()`, `waitVanish()`, and `findAll()`. I added the type check for either ints or floats in `wait()` and updated the unit tests accordingly. 

These changes are in `develop` for now, I'll get them rolled out to production soon.

**Comment by glitchassassin** [comment]
This fix has been rolled out to Pypi.

**Comment by nejch** [comment]
Thanks! Ah, makes sense to have it only in `wait()`. And sorry for the messy PR I submitted, I closed that when I saw what I did, oops.

**Comment by glitchassassin** [comment]
It was a great starting place, thank you.
