### ISSUE TITLE
Update Documentation for set/getClipboard?

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#74]
The method that used to work in previous version:

`platformManager.getClipboard`

does not seem to work anymore. Documentation still states setClipboard & getClipboard methods as available in platform manager.

Is the preferred way now using Screen object (as I saw methods present there)?

Is there a way to ask questions like this, instead of creating issues?

**Comment by glitchassassin** [comment]
This is the correct place to ask, as the documentation needs to be updated. I tried to change it in a previous release and didn't check to make sure ReadTheDocs updated correctly.

The preferred way is to use `App.getClipboard()` instead (though as you noted, the method is also present in Region objects, including Screen).

After review, I left out Sikuli's undocumented App.setClipboard() method, so I'll get that added in the next release.

Thanks for the report!

**Comment by glitchassassin** [comment]
Holy cow, they haven't been updating for months. Good thing we caught this. I think I know where the issue is, we'll see if this fixes it.

**Comment by glitchassassin** [comment]
This has been pushed out as a hotfix. Thanks again for the report!
