### ISSUE TITLE
click() target not an optional argument

### ISSUE THREAD

**Issue by nejch** [glitchassassin/lackey#77]
In sikulix, `click()` uses the current region's `lastMatch` if no argument is given. Useful for "wait for x and then click it" scenarios and to just let `wait() ` handle wait timeouts:
```
wait('startmenu.png')
click()
```
Lackey's `click()` target argument is not optional though:
```
>>> wait('startmenu.png')
[info] Found match for pattern 'startmenu.png' at (9,1403) with confidence (1.0). Target at (23,1418)
Match[9,1403 29x30] score=1.000000, target=(0, 0)
>>> click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: click() missing 1 required positional argument: 'target'
```
Looks like the code is already there and just setting the default argument value to `None` fixes this for me.

Note that it then raises a `TypeError` if no `lastMatch` is stored. 
```
>>> click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "RegionMatching.py", line 568, in click
    raise TypeError("click expected Pattern, String, Match, Region, or Location object")
TypeError: click expected Pattern, String, Match, Region, or Location object
```
Sikuli would just click on the default click point, i.e. the center of the current region/screen.
This only works with lackey if a Region object is explicitly passed as the target (just tested this with `click(Screen(0))`).

**Comment by glitchassassin** [comment]
Good call. This should look like the following:

    def click(self, target=None, modifiers=""):
        """ Moves the cursor to the target location and clicks the default mouse button. """
        if target is None:
            target = self._lastMatch or self # Whichever one is not None

I'll make the modification to the other mouse routines as well. Thanks for the report!

**Comment by nejch** [comment]
Great, just tried with `develop`. Thanks!
