### ISSUE TITLE
App not initialized properly when selected by title

### ISSUE THREAD

**Issue by nejch** [glitchassassin/lackey#79]
When an App object is created by title, it should match an existing window if one is open.
Currently `open()` needs to be called explicitly after to initialize it properly.

Assuming notepad is open:

```
>>> a = App('Notepad')
[debug] Creating App by string (Notepad)
>>> print(a)
[-1: ()] Notepad
>>> a.open()
[9288:notepad.exe (Untitled - Notepad)] Notepad
```

Whereas in Sikuli just running `App('Notepad')` is enough:
```
[debug] WinUtil.getApp: Notepad
[debug] App.create: [9288:notepad.exe]
[debug] WinUtil.getApp: 9288
[9288:notepad.exe (Untitled - Notepad)] Notepad
```

**Comment by glitchassassin** [comment]
Good catch, thanks! Adding you to the contributors list. =)

**Comment by nejch** [comment]
Ah! Thank you! :)

**Comment by glitchassassin** [comment]
Fixed in latest release.
