### ISSUE TITLE
how to use scroll down?

### ISSUE THREAD

**Issue by wangtubs** [glitchassassin/lackey#81]
hi, I find http://lackey.readthedocs.io/en/latest/lackey.html#lackey-mouse-class in the mouse class, there is wheel down method, can you give me an example to wheel down the scroll?
thanks

**Comment by nejch** [comment]
I think ideally you could just use e.g. `wheel(Mouse.WHEEL_DOWN, 1)`. But there seems to be a minor bug in `Region`'s wheel method. 

So you can create a mouse instance and call the method with the following 2 arguments:
- direction (`Mouse.WHEEL_UP` or `Mouse.WHEEL_DOWN` for up or down)
- steps (an integer, number of steps to scroll)

This works for me:
```
m = Mouse()
m.wheel(Mouse.WHEEL_DOWN, 1)	# Scrolls down one step
m.wheel(Mouse.WHEEL_UP, 5)	# Scrolls up five steps
```

**Comment by nejch** [comment]
Regarding the implementation in `Region`, seems like `PSRML` should be an optional argument e.g.:
```
def wheel(self, direction, steps, PSRML=None):
    """ Clicks the wheel the specified number of ticks """
    if PSRML is not None:
        self.mouseMove(PSRML)
    mouse.wheel(direction, steps
```
Might be good to check if there's any other catch here though, since PSRML is pretty broad.

**Comment by glitchassassin** [comment]
Just verified that the PSRML is optional in Sikuli (despite the documentation to the contrary).

It's not quite as simple as making it an optional argument in Python, to preserve compatibility, as we have to support the following argument lists:

    (int direction, int steps)
    (PFRML target, int direction, int steps)
    (PFRML target, int direction, int steps, int stepDelay)

This just means we have to figure out which pattern of parameters have been passed. (There are a few other methods like this as well).

I'll get this fixed for the next release. Thanks for the report!

**Comment by glitchassassin** [comment]
Fixed in latest release. Feel free to re-open if you have more questions.
