### ISSUE TITLE
App title matching is not case-insensitive

### ISSUE THREAD

**Issue by nejch** [glitchassassin/lackey#82]
Lackey currently does not perform a case-insensitive match on `App` titles, which I believe was the intended behavior, like in sikuli.

With notepad open:
```
>>> App('Notepad')
[5732:notepad.exe (Untitled - Notepad)] Notepad
>>> App('notepad')
[-1: ()] notepad
```

**Comment by glitchassassin** [comment]
Merged the pull request. Thanks!

**Comment by glitchassassin** [comment]
Fixed in latest release.
