### ISSUE TITLE
atMouse() is not available - Undocumented Sikuli methods

### ISSUE THREAD

**Issue by jazz1215** [glitchassassin/lackey#85]
Hi,

In my scripts there is a need to click at the current mouse location (after the previous click triggers a change in the original pattern).  I found a Sikuli solution which mentioned atMouse():
https://answers.launchpad.net/sikuli/+question/244304

However, it seems to be missing in Lackey.  It is not mentioned in http://doc.sikuli.org either.  So not sure if it's an extra feature of SikuliX.

The workaround is to use click(reg.getLastMatch()).

Thanks

**Comment by glitchassassin** [comment]
Hmm... I'll have to go over the Sikuli source code instead of relying solely on the documentation. Thanks for the tip.

Fortunately, clicking at the last match should already be implemented in the latest release:

    click() # Will click at the last matched location of the global Screen region
    reg.click() # Will click at the last matched location for the 'reg' region

If these don't work, let me know - there may be other bugs here.

To get the mouse's actual current location, you can call `getPos()` on the internal `Mouse` handler. This returns a Location object, which can be fed directly to `click()`:

    click(Mouse().getPos())

Be aware that this functionality may change in the future as Mouse is an internal class and its API is not guaranteed. I'll get `atMouse()` implemented soon.

**Comment by glitchassassin** [comment]
Implemented a few methods. Listing remaining missing methods below (some may be experimental or deprecated, in which case they can be skipped).

- Region()
  - setImageMissingHandler()
  - getObserveScanRate()
  - setObserveScanRate()
  - setRepeatWaitTime()
  - getRepeatWaitTime()
  - showScreens()
  - resetScreens()
  - getTarget()
  - setCenter()
  - setTopLeft()
  - setTopRight()
  - setBottomLeft()
  - setBottomRight()
  - setSize()
  - setRect()
  - getROI()
  - setLocation()
  - add()
  - saveScreenCapture()
  - getLastScreenImage()
  - saveLastScreenImage()
  - contains()
  - asOffset()
  - rightAt()
  - leftAt()
  - aboveAt()
  - belowAt()
  - union()
  - intersection()
  - highlight() [overloads]
  - findAllByRow()
  - findAllByColumn()
  - findBest()
  - compare()
  - findText() [OCR function?]
  - findAllText() [OCR function?]
  - dragDrop() [overloads]
  - mouseUp() [overloads]
  - mouseMove() [overloads]
  - atMouse()
  - write()
  - delayType()
  - text() [OCR function?]
  - listText() [OCR function?]

**Comment by glitchassassin** [comment]
## Location

- getScreen()
- getMonitor()
- isOtherScreen()
- setOtherScreen()
- getColor()
- getOffset()
- grow()
- moveFor()
- translate()
- moveTo()
- move()
- copyTo()
- hover()
- click()
- doubleClick()
- rightClick()

**Comment by glitchassassin** [comment]
## Mouse

Mostly internal class, but should be implemented to match Sikuli for consistency

- at()
- reset()
- getMouseMovedResponse()
- setMouseMovedAction()
- setMouseMovedCallback()
- setMouseMovedHighlight()
- hasMoved()
- click()
- move()
- down()
- up()
- wheel()

**Comment by glitchassassin** [comment]
## Pattern

- isImagePattern()
- isValid()
- setFilename()
- getSimilar()
- setImage()
- setTimeAfter()
- getTimeAfter()

**Comment by glitchassassin** [comment]
## Screen

- getCurrentID()
- all()
- as()
- setAsScreenUnion()
- setAsScreen()
- getScreen()
- showMonitors()
- resetMonitors()
- getPrimaryId()
- getPrimaryScreen()
- getScreen()
- getID()
- getIdFromPoint()
- newRegion()
- getLastScreenImageFromScreen()
- newLocation()
- cmdCapture()
- captureforHighlight()
- doPrompt()
- closePrompt()
- resetPrompt()
- hasPrompt()
- userCapture()
- saveCapture()
- showTarget()

**Comment by glitchassassin** [comment]
Man, there are a lot of undocumented methods in Sikuli.

I'll work my way through these as I have time. If anyone else wants to start on some of them, the original Java classes that contain these methods [are over at the Sikuli repository](https://github.com/RaiMan/SikuliX-2014/tree/master/API/src/main/java/org/sikuli/script).

**Comment by glitchassassin** [comment]
I burned through most of these today and reconciled any issues with the current test cases. I've also added a Powershell script to build a combined coverage report for Python 2.7 and 3.5. I'll be using this to build new test cases covering the new methods we've added.

If anyone wants to help, feel free to submit a pull request to add some of these test cases!

**Comment by glitchassassin** [comment]
All except OCR and overlay methods should now be implemented with version 0.7.0. Those will be tracked in other tasks.
