### ISSUE TITLE
how to move the mouse to a location?

### ISSUE THREAD

**Issue by wangtubs** [glitchassassin/lackey#86]
can you give me a demo?

**Comment by glitchassassin** [comment]
You can use `hover`:

    from lackey import *
    hover(Location(100,200)) # If you know the exact coordinates
    hover("notepad.png") # If you have a target image
    hover() # To move the mouse to the last found image, or the center of the screen if no images have been found yet

**Comment by glitchassassin** [comment]
Assuming this helped - if not, feel free to reopen. Closing issue.

**Comment by DanHarty** [comment]
How do I move the mouse relative to its current location?

**Comment by glitchassassin** [comment]
Hi Dan,

Check out the docs here:

https://lackey.readthedocs.io/en/latest/lackey.html#lackey.Mouse.move
