### ISSUE TITLE
[DOC] Windows virtual box config to install lackey

### ISSUE THREAD

**Issue by DeChrish** [glitchassassin/lackey#87]
@glitchassassin 

Any Readme file for installing lackey in windows virtual box hosed in Mac OSx.

**Comment by glitchassassin** [comment]
Should be the same as installing it on a regular Windows machine - install Python, then use `pip` to install Lackey.

Let me know if you have any issues!

**Comment by DeChrish** [comment]
@glitchassassin - straight fwd.  thanks.
