### ISSUE TITLE
click method doesn't click

### ISSUE THREAD

**Issue by wangtubs** [glitchassassin/lackey#88]
I find the click method doesn't work well on iTunes client. I saw many times,  the mouse just move the location, but doesn't click. I think the mouse should first set focus on the location and do the click event.
hope you fix this bug soon.

**Comment by glitchassassin** [comment]
I've seen this issue sometimes when the script isn't running with administrator privileges; without admin rights, the script can only send events to user-mode programs.

Try running it as an administrator (you can right-click on Powershell/cmd and "run as administrator", then call your script) and let me know if that works for you.

**Comment by wangtubs** [comment]
I already run it as an administrator.

**Comment by glitchassassin** [comment]
Great. Is the issue happening consistently in a particular section of iTunes?

**Comment by wangtubs** [comment]
it happens consistently. but not always.

**Comment by glitchassassin** [comment]
Hmm. Can you try attaching some screenshots of the locations that are giving you fits? I'll try to duplicate the issue on my end.

**Comment by wangtubs** [comment]
![image](https://cloud.githubusercontent.com/assets/9078477/24800669/4a28402a-1ba1-11e7-8289-d081deedd453.png)
in the pic, I want to click the "Editor's Choice". it sometimes work, many times don't, only move the mouse to the location.

**Comment by glitchassassin** [comment]
I've been trying to duplicate this issue, but without success so far. I'm able to click the Editors' Choice link every time, regardless of which window has the focus.

What happens before this click? Are you working in any settings dialogs?

**Comment by randu1459** [comment]
@wangtubs If you could provide a snippet of your script leading up to the click method, perhaps we can get to the bottom of this. Thanks!

**Comment by glitchassassin** [comment]
Closing as not reproducible. If you're able to turn up any more details, feel free to re-open.

Thanks!
