### ISSUE TITLE
Sikuli submodule imports and image path

### ISSUE THREAD

**Issue by nejch** [glitchassassin/lackey#96]
This is just something I noticed while converting my sikuli scripts.

Sikuli has its own import mechanism to mimic Python package imports, allowing you to import a `submodule.sikuli` folder with a `submodule.py` and any related images inside, and adds them to the image path.

So if you want to structure your scripts, e.g. by functionality like below, you can use ``import submodule`` in your main `module.sikuli`:
```
├── module.sikuli/
│   ├── module.py
│   ├── image.png
│   ├── submodule.sikuli/
│   │   ├── submodule.py
│   │   ├── image2.png
```
For lackey I had to change this back to a normal Python subpackage structure - remove `.sikuli` from folder names and rename `submodule.py` to  `__init__.py` inside:
```
├── module/
│   ├── module.py
│   ├── image.png
│   ├── submodule/
│   │   ├── __init__.py
│   │   ├── image2.png
```
This is all good and makes more sense in pure Python to me, but the subfolders are not added to the image path automatically on import, like in sikuli (so it can't find those images). This hack works for me (`__init__.py` in each of the subpackages):
```
from lackey import *
addImagePath(os.path.join(getBundlePath(), __name__))
```
Not sure yet if/how this could be changed but just wanted to note this. Maybe if lackey adds any subpackages found in the main module's directory to the image path on import?

**Comment by nejch** [comment]
[Here](https://answers.launchpad.net/sikuli/+question/233331) is RaiMan's explanation of sikuli's import process for reference:

> Sikuli as a convenience feature allows to import other .sikuli scripts as "modules". Together with this convenience, Sikuli adds the .sikuli folder to the image path, so you do not need to handle the submodule images separately.
> 
> This is implemented internally as a hook into the Jython import process.
> 
> lets make an example:
> You made submodule.sikuli, that contains some supporting functions to be used all over the place.
> 
> the usage would be e.g.
> from submodule import *
> 
> This looks exactly like a normal Python import, that should find and import a file named submodule.py from sys.path
> 
> But since we are using Sikuli to run our scripts:
> - Sikuli first searches for a submodule.sikuli on sys.path.
> - then it tells the Jython import, to import the contained submodule.py
> - and it adds submodule.sikuli to Sikuli's image path
> 
> If Sikuli does not find a submodule.sikuli, it delegates the further processing to Jython import, which might or might not find a submodule.py

**Comment by glitchassassin** [comment]
I think this can be implemented with [an import hook](https://www.python.org/dev/peps/pep-0302/). I'll do some research and see.

**Comment by nejch** [comment]
I'm looking at hooks now as well, I can open a PR if I get it working soon.
I found [this](https://github.com/kragniz/json-sempai) hilarious working example. :)

**Comment by glitchassassin** [comment]
Finally getting around to this!

**Comment by glitchassassin** [comment]
Working in Python 3. Of course, some of this functionality is newer, so we need a Python 2.7 fallback.
