### ISSUE TITLE
[Question] FOREVER constant

### ISSUE THREAD

**Issue by xtfr** [glitchassassin/lackey#99]
I used [FOREVER](https://github.com/sikuli/sikuli/blob/develop/sikuli-script/src/main/java/org/sikuli/script/Constants.java#L9) quite often in Sikuli and noticed that Lackey has not yet implemented this as I got NameError while porting my Sikuli scripts to Lackey.

I probably can write a function or wrapper for a workaround, but just wondering whether FOREVER will be implemented in the future? Thanks!

**Comment by xtfr** [comment]
Thanks for the quick fix! I tested it and confirmed that wait('imgname', FOREVER) and waitVanish('imgname', FOREVER) are working the same way as Sikuli's. Cheers.

**Comment by glitchassassin** [comment]
This issue has been fixed with v0.7.0.
